#! /bin/bash
#
#$Author: ee364b08 $
#$Date: 2016-01-13 15:29:04 -0500 (Wed, 13 Jan 2016) $
#$Revision: 84723 $
#$HeadURL: svn+ssh://ece364sv@ecegrid-thin1/home/ecegrid/a/ece364sv/svn/S16/students/ee364b08/Lab00/Script3 $
#$Id: Script3 84723 2016-01-13 20:29:04Z ee364b08 $

Num_Of_Param=$#
Param_Values=$@

for (( I=$1; I>=0; I-- ))
   do
       if (( $I%3 == 0 ))
       then
        echo $I
    fi
   done
exit 0
